image: registry.forge.uclouvain.be/inl/containers/runner-bird

stages:
  - build

quic_socket_api-build:
  stage: build
  script:
    - echo "Compiling the QUIC socket API"
    - git -C quic_socket_api remote set-url origin https://gitlab-ci-token:$CI_JOB_TOKEN@forge.uclouvain.be/inl/routing-over-quic/quic_socket_api.git
    - git -C quic_socket_api remote get-url origin
    - git -C quic_socket_api submodule update --init --recursive
    - git -C quic_socket_api/submodules/picoquic remote set-url origin https://gitlab-ci-token:$CI_JOB_TOKEN@forge.uclouvain.be/inl/routing-over-quic/picoquic.git
    - git submodule update --init --recursive
    - ls -al quic_socket_api
    - cd quic_socket_api
    - if [[ -d build ]]; then rm -rf build; fi
    - mkdir -p build/include
    - mkdir -p lib/lib
    - cd build
    - apt-get install -y python3.6-dev
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=lib -DCMAKE_C_COMPILER=/usr/bin/clang-14 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-14 -DCMAKE_MAKE_PROGRAM=make ..
    - make -j$(nproc) all install
    - ln -s $(pwd)/_deps/picotls-build/*.a $(pwd)/lib/lib/
  only:
    - picoquic
  artifacts:
    paths:
      - quic_socket_api/build/

bird-build:
  stage: build
  dependencies:
    - quic_socket_api-build
  only:
    - picoquic
  script:
    - echo "Compiling BIRD embedding the socket API"
    - autoupdate
    - autoreconf
    - ls quic_socket_api/build/lib/lib
    - ./configure PICOQUIC_LIB=quic_socket_api/build/lib/lib PICOQUIC_SOCK_API_LIB=quic_socket_api/build/lib/lib PICOQUIC_SOCK_API_HDR=quic_socket_api/include/
    - make
  artifacts:
    paths:
      - bird
      - birdc
